# Generated by Django 5.2.3 on 2025-06-24 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('hora_emision', models.TimeField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaSeguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteBoletas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_registro', models.TimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteCaja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_registro', models.TimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('hora_emision', models.TimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.boleta')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField(blank=True, null=True)),
                ('monto_devuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_de_nota', to='gestion_ventas.notacredito')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReporteBoleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.boleta')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.reporteboletas')),
            ],
            options={
                'verbose_name': 'Detalle Reporte Boleta',
                'verbose_name_plural': 'Detalles Reportes Boleta',
            },
        ),
        migrations.CreateModel(
            name='DetalleReporteCaja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('monto_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('denominacion', models.ForeignKey(db_column='denominación_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.denominacion')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.reportecaja')),
            ],
            options={
                'verbose_name': 'Detalle Reporte Caja',
                'verbose_name_plural': 'Detalles Reportes Caja',
            },
        ),
        migrations.CreateModel(
            name='ReporteEgresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('hora_registro', models.TimeField()),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_nota_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_reporte_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteCierreCaja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('hora_registro', models.TimeField()),
                ('descuadre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razon', models.TextField(blank=True, null=True)),
                ('reporte_boletas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.reporteboletas')),
                ('reporte_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.reportecaja')),
                ('reporte_egresos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.reporteegresos')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.usuario'),
        ),
        migrations.AddField(
            model_name='reporteboletas',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.usuario'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.usuario'),
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_parcial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.boleta')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Boleta',
                'verbose_name_plural': 'Detalles de Boleta',
                'unique_together': {('id_boleta', 'codigo_producto')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioPreguntaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_hash', models.CharField(max_length=255)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.preguntaseguridad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Pregunta Respuesta',
                'verbose_name_plural': 'Usuarios Preguntas Respuestas',
                'unique_together': {('usuario', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioPrivilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.privilegio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Privilegio',
                'verbose_name_plural': 'Usuarios Privilegios',
                'unique_together': {('usuario', 'privilegio')},
            },
        ),
    ]
